### PR TITLE
Reimplement signature check without pefile

### PR DESCRIPTION
**Pull request by catlee**

### CODE REVIEW

**Comment by catlee** [comment]
Will add some tests for the new function

**Comment by catlee** [comment]
unsigned32.exe comes from other-licenses/nsis/Plugins/InvokeShellVerb.dll
unsigned64.exe comes from third_party/rust/libloading/tets/nagisa64.dll

I'd love to find other sources of test files...or even generate them for this purpose.

**Comment by escapewindow** [comment]
Schweet. I can stamp this if you'd like.

- we just pushed out 3.1.2 for bug 1380536, so we need to bump the version higher
- once this lands, we can remove pefile from the signing scriptworker deps in puppet [!]
- how confident are you in this? we could land this sooner so we have more baking time, and possibly see signing issues in Nightly, or we could hold off til post-57 and land early in the cycle... but it's not tree specific, so it would affect betas/chemspills right away. I think I just convinced myself we should land this sooner.

**Comment by catlee** [comment]
I'm pretty confident. I ran this over all the exe and dll files I could find, and it matches pefile's behavior. Can we roll it out to the dep workers first?

**Comment by catlee** [comment]
Want me to rebase / squash instead of merging it in?

**Comment by escapewindow** [comment]
> I'm pretty confident. I ran this over all the exe and dll files I could find, and it matches pefile's behavior. Can we roll it out to the dep workers first?

Cool! Puppet has the signing scriptworkers modules all configured in the same shared place, so we can't roll out separately without either refactoring or pointing some workers at a puppet env. Do you want that?

> Want me to rebase / squash instead of merging it in?
I don't have strong opinions about rebase/squash vs merge in this repo.

**Pull request merged**
